<a href="https://colab.research.google.com/github/hliu71/citation_function_classification/blob/main/Copy_of_text_classification_of_sdp_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# mount

In [2]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# import module
import pandas as pd


In [4]:
  
# read the csv file
results_train = pd.read_csv('/content/drive/MyDrive/data/sdp2022/task1_train_dataset.csv')
  
# display dataset
print(results_train)

       index                                              title  \
0          0  Activation of nitrofurazone by azoreductases: ...   
1          1  Organisation and delivery of home care re-able...   
2          2  Relationships between anthocyanins and other c...   
3          3  New Insights into the Mechanisms of Water-Stre...   
4          4  Extensive chordate and annelid macrosynteny re...   
...      ...                                                ...   
51555  51555  BALB/c mice deficient in CD4(+) T cell IL-4R a...   
51556  51556         The Afterlife of Parliamentary Sovereignty   
51557  51557  Metabolomic Profiling of In Vivo Plasma Respons...   
51558  51558  Constant flux relation for diffusion-limited c...   
51559  51559  Sequence determinants for the tandem recogniti...   

            first_author                                        description  \
0            M Nakanishi                                                NaN   
1                  Allen             

In [5]:
df_train = results_train[['title','theme']]
df_train

title  \
0      Activation of nitrofurazone by azoreductases: ...   
1      Organisation and delivery of home care re-able...   
2      Relationships between anthocyanins and other c...   
3      New Insights into the Mechanisms of Water-Stre...   
4      Extensive chordate and annelid macrosynteny re...   
...                                                  ...   
51555  BALB/c mice deficient in CD4(+) T cell IL-4R a...   
51556         The Afterlife of Parliamentary Sovereignty   
51557  Metabolomic Profiling of In Vivo Plasma Respons...   
51558  Constant flux relation for diffusion-limited c...   
51559  Sequence determinants for the tandem recogniti...   

                                                   theme  
0      Allied Health Professions, Dentistry, Nursing ...  
1                          Social Work and Social Policy  
2               Agriculture, Veterinary and Food Science  
3               Earth Systems and Environmental Sciences  
4                                    Biological Sciences  
...                                                  ...  
51555  Allied Health Professions, Dentistry, Nursing ...  
51556                                                Law  
51557           Agriculture, Veterinary and Food Science  
51558                              Mathematical Sciences  
51559  Allied Health Professions, Dentistry, Nursing ...  

[51560 rows x 2 columns]

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51560 entries, 0 to 51559
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   title   51560 non-null  object
 1   theme   51560 non-null  object
dtypes: object(2)
memory usage: 805.8+ KB


# prepare sentences and ys

In [7]:
sentences = df_train['title'].values
sentences

array(['Activation of nitrofurazone by azoreductases: multiple activities in one enzyme',
       'Organisation and delivery of home care re-ablement : what makes a difference?',
       'Relationships between anthocyanins and other compounds and sensory acceptability of Hibiscus drinks',
       ...,
       'Metabolomic Profiling of In Vivo Plasma Responses to DioxinAssociated Dietary Contaminant Exposure in Rats: Implications for Identification of Sources of Animal and Human Exposure',
       'Constant flux relation for diffusion-limited cluster-cluster aggregation',
       'Sequence determinants for the tandem recognition of UGU and CUG rich RNA elements by the two N-terminal RRMs of CELF1'],
      dtype=object)

In [8]:
len(sentences)

51560

In [9]:
y = df_train['theme'].values
y

array(['Allied Health Professions, Dentistry, Nursing and Pharmacy',
       'Social Work and Social Policy',
       'Agriculture, Veterinary and Food Science', ...,
       'Agriculture, Veterinary and Food Science',
       'Mathematical Sciences',
       'Allied Health Professions, Dentistry, Nursing and Pharmacy'],
      dtype=object)

In [40]:
import tensorflow as tf

train_labels = tf.one_hot(y)

TypeError: ignored

# train_test_split 

In [10]:
from sklearn.model_selection import train_test_split

sentences_train, sentences_test, y_train, y_test = train_test_split(sentences, y, test_size=0.25, random_state=1000)
# python - scikit-learn random state in splitting dataset - Stack Overflow
# https://stackoverflow.com/questions/42191717/scikit-learn-random-state-in-splitting-dataset# 

In [11]:
y_train

array(['Economics and Econometrics', 'Physics',
       'Psychology, Psychiatry and Neuroscience', ...,
       'Architecture, Built Environment and Planning', 'Physics',
       'Computer Science and Informatics'], dtype=object)

In [12]:
y_test

array(['Clinical Medicine', 'Law', 'English Language and Literature', ...,
       'Allied Health Professions, Dentistry, Nursing and Pharmacy',
       'Clinical Medicine', 'Business and Management Studies'],
      dtype=object)

In [33]:
len(y_train)

38670

In [34]:
y_train[1]

'Physics'

In [ ]:
train_labels = 

# 0.4350 - CountVectorizer

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features=5000,max_df=0.05)
vectorizer.fit(sentences_train)

X_train = vectorizer.transform(sentences_train)
X_test  = vectorizer.transform(sentences_test)
X_train

<38670x5000 sparse matrix of type '<class 'numpy.int64'>'
	with 280392 stored elements in Compressed Sparse Row format>

## LogisticRegression

In [20]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train, y_train)
score = classifier.score(X_test, y_test)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [21]:

print("Accuracy: %.4f" %score)

Accuracy: 0.4350


In [23]:
y_pred = classifier.predict(X_test)

In [24]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 64   3  14 ...   0   1   0]
 [  3  90  27 ...   0   1   0]
 [ 10  15 256 ...   4  11   0]
 ...
 [  0   1   4 ...  20   0   0]
 [  0   2  31 ...   1  74   0]
 [  0   0   2 ...   2   0   0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                                                                               precision    recall  f1-score   support

             Aeronautical, Mechanical, Chemical and Manufacturing Engineering       0.28      0.21      0.24       299
                                     Agriculture, Veterinary and Food Science       0.40      0.30      0.34       299
                   Allied Health Professions, Dentistry, Nursing and Pharmacy       0.30      0.29      0.30       882
                                         Anthropology and Development Studies       0.20      0.10      0.14        97
                                 Architecture, Built Environment and Planning       0.37      0.35      0.36       205
                                                                 Area Studies       0.12      0.05      0.07        64
                                 Art and Design: History, Practice and Theory       0.20      0.11      0.14        94
                                               

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#0.4350 - fit vs fit_transform

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features=5000,max_df=0.05)
vectorizer.fit_transform(sentences_train) 

X_train = vectorizer.transform(sentences_train)
X_test  = vectorizer.transform(sentences_test)
X_train

<38670x5000 sparse matrix of type '<class 'numpy.int64'>'
	with 280392 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train, y_train)
score = classifier.score(X_test, y_test)
print("Accuracy: %.4f" %score)

Accuracy: 0.4350


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


# .toarray()

In [ ]:
type(X_train)

scipy.sparse.csr.csr_matrix

In [ ]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train[0]

<1x5000 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

# 0.4556 - TfidfVectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)
vectorizer.fit(sentences_train)

X_train = vectorizer.transform(sentences_train)
X_test  = vectorizer.transform(sentences_test)
X_train

<38670x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 376521 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train, y_train)
score = classifier.score(X_test, y_test)
print("Accuracy: %.4f" %score)

Accuracy: 0.4556


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


# 0.4383 - TfidfVectorizer with and ngram

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(token_pattern=r'\b\w{2,}\b',
                       min_df=1, max_df=0.1, ngram_range=(1,2),max_features=5000)
vectorizer.fit(sentences_train)

X_train = vectorizer.transform(sentences_train)
X_test  = vectorizer.transform(sentences_test)
X_train

<38670x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 351663 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train, y_train)
score = classifier.score(X_test, y_test)
print("Accuracy: %.4f" %score)

Accuracy: 0.4383


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


# 0.4477 - TfidfVectorizer with stopwords and ngram 

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english',token_pattern=r'\b\w{2,}\b',
                       min_df=1, max_df=0.1, ngram_range=(1,2),max_features=5000)
vectorizer.fit(sentences_train)

X_train = vectorizer.transform(sentences_train)
X_test  = vectorizer.transform(sentences_test)
X_train

<38670x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 271618 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train, y_train)
score = classifier.score(X_test, y_test)
print("Accuracy: %.4f" %score)

Accuracy: 0.4477


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


# random forest

In [14]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=1000, random_state=0,max_depth = 6)
classifier.fit(X_train, y_train) 



RandomForestClassifier(max_depth=6, n_estimators=1000, random_state=0)

In [16]:
score = classifier.score(X_test, y_test)
score

0.13328161365399535

In [17]:
y_pred = classifier.predict(X_test)


In [18]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 22 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                                                                               precision    recall  f1-score   support

             Aeronautical, Mechanical, Chemical and Manufacturing Engineering       0.00      0.00      0.00       299
                                     Agriculture, Veterinary and Food Science       0.00      0.00      0.00       299
                   Allied Health Professions, Dentistry, Nursing and Pharmacy       0.33      0.02      0.05       882
                                         Anthropology and Development Studies       0.00      0.00      0.00        97
                                 Architecture, Built Environment and Planning       0.00      0.00      0.00       205
                                                                 Area Studies       0.00      0.00      0.00        64
                                 Art and Design: History, Practice and Theory       0.00      0.00      0.00        94
                                               

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.13328161365399535


# pipeline

# todense()

In [ ]:
X_train = X_train.todense()
X_test = X_test.todense()

In [ ]:
X_train = X_train.todense()


In [ ]:
X_train

<38670x5000 sparse matrix of type '<class 'numpy.int64'>'
	with 280392 stored elements in Compressed Sparse Row format>

In [ ]:
type(X_train)

scipy.sparse.csr.csr_matrix

In [ ]:
X_test

<12890x5000 sparse matrix of type '<class 'numpy.int64'>'
	with 91677 stored elements in Compressed Sparse Row format>

# Keras

In [25]:
from keras.models import Sequential
from keras import layers

In [26]:
input_dim = X_train.shape[1]  # Number of features

input_dim

5000

In [30]:
model = Sequential()
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(36, activation='sigmoid'))

In [31]:
model.compile(loss='binary_crossentropy', 
              optimizer='adam', 
              metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 10)                50010     
                                                                 
 dense_3 (Dense)             (None, 36)                396       
                                                                 
Total params: 50,406
Trainable params: 50,406
Non-trainable params: 0
_________________________________________________________________


In [32]:
history = model.fit(X_train, y_train,
                    epochs=10,
                    verbose=False,
                    validation_data=(X_test, y_test),
                    batch_size=10)

ValueError: ignored

# Tensorflow

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
len(X_train[0])

TypeError: ignored

In [ ]:
print("Training entries: {}, labels: {}".format(len(X_train), len(y_train)))


Training entries: 38670, labels: 38670


In [ ]:
print(X_train[2])


  (0, 253)	1
  (0, 1973)	1
  (0, 2196)	1
  (0, 2657)	1
  (0, 2826)	1
  (0, 2987)	1
  (0, 3116)	1
  (0, 4049)	1
  (0, 4452)	1
  (0, 4945)	1


In [ ]:
len(X_train[0]), len(X_train[1])


(1, 1)

In [ ]:
history = model.fit(partial_x_train,
                    partial_y_train,
                    epochs=40,
                    batch_size=512,
                    validation_data=(x_val, y_val),
                    verbose=1)

# New Section